version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: inventory_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: inventory_management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - inventory_network

  backend:
    build: ./server
    container_name: inventory_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://user:<db_password>@test.oubyqth.mongodb.net/?retryWrites=true&w=majority&appName=test
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - inventory_network

  frontend:
    build: .
    container_name: inventory_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inventory_network

volumes:
  mongodb_data:

networks:
  inventory_network:
    driver: bridge
